// TODO : we need to cahnge actions to Enum

export enum AuthTypes {
  USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
  USER_LOGIN_AUTH = 'USER_LOGIN_AUTH',
  FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS',
  USER_LOGIN_LOADING = 'USER_LOGIN_LOADING',
  USER_RESET_LOADING = 'USER_RESET_LOADING',
  USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS',
  USER_LOGOUT = 'USER_LOGOUT',
}

export enum AuthErrorTypes {
  LOADING = 'AUTH_LOADING',
  AUTH_ERROR = 'AUTH_ERROR',
  AUTH_GENCODE_ERROR = 'AUTH_GENCODE_ERROR',
  FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR',
  RESET_ERROR = 'RESET_ERROR',
}

export enum SetPasswordType {
  SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS',
  SET_PASSWORD_FAILURE = 'SET_PASSWORD_FAILURE',
}

export enum HeaderTypes {
  GET_USER_CLIENTS_LIST_REQUEST = 'GET_USER_CLIENTS_LIST_REQUEST',
  GET_USER_CLIENTS_LIST_SUCCESS = 'GET_USER_CLIENTS_LIST_SUCCESS',
  SELECT_ACTIVE_CLIENT = 'SELECT_ACTIVE_CLIENT',
  SELECT_ACTIVE_RELOAD = 'SELECT_ACTIVE_RELOAD',
  USER_DETAILS = 'USER_DETAILS',
  UPDATE_DEFAULT_CURRENCY = 'UPDATE_DEFAULT_CURRENCY',
}

export enum DefaultTypes {
  ERROR = 'ERROR',
  APP_ERROR = 'APP_ERROR',
  CLEAR_ERROR = 'CLEAR_ERROR',
  PARTNER_DETAILS = 'PARTNER_DETAILS',
}

export enum SnackbarTypes {
  SNACKBAR_DISMISS = 'SNACKBAR_DISMISS',
  SNACKBAR_DISMISS_ALL = 'SNACKBAR_DISMISS_ALL',
  SNACKBAR_MESSAGE = 'SNACKBAR_MESSAGE',
}

export enum TransactionHistoryActionType {
  TRANSACTION_HISTORY_DATA_REQUEST = 'TRANSACTION_HISTORY_DATA_REQUEST',
  TRANSACTION_HISTORY_DATA_SUCCESS = 'TRANSACTION_HISTORY_DATA_SUCCESS',
  TRANSACTION_HISTORY_DATA_FAILURE = 'TRANSACTION_HISTORY_DATA_FAILURE',
  TRANSACTION_HISTORY_UPDATE_SUCCESS = 'TRANSACTION_HISTORY_UPDATE_SUCCESS',
}
export enum BeneficiaryTypes {
  GET_BENEFICIARY_DETAILS_REQUEST = 'GET_BENEFICIARY_DETAILS_REQUEST',
  GET_BENEFICIARY_DETAILS_SUCCESS = 'GET_BENEFICIARY_DETAILS_SUCCESS',
  GET_BENEFICIARY_DETAILS_FAILURE = 'GET_BENEFICIARY_DETAILS_FAILURE',
}

export enum PaymentTypes {
  LOADING = 'PAYMENT_LOADING',
  GET_LOCK_FX_RATE_REQUEST = 'GET_LOCK_FX_RATE_REQUEST',
  GET_LOCK_FX_RATE_REQUEST_ERROR = 'GET_LOCK_FX_RATE_REQUEST_ERROR',
  EXCHANGE_VALUE_SET = 'PAYMENT_EXCHANGE_VALUE_SET',
  PAYMENT_METHOD = 'PAYMENT_METHOD',
}

export enum TransactionHistoryCSVDownloadActionTypes {
  TRANSACTION_HISTORY_CSV_DOWNLOAD_REQUEST = 'TRANSACTION_HISTORY_CSV_DOWNLOAD_REQUEST',
  TRANSACTION_HISTORY_CSV_DOWNLOAD_SUCCESS = 'TRANSACTION_HISTORY_CSV_DOWNLOAD_SUCCESS',
  TRANSACTION_HISTORY_CSV_DOWNLOAD_FAILURE = 'TRANSACTION_HISTORY_CSV_DOWNLOAD_FAILURE',
}

export enum AccountTypes {
  LOADING = 'ACCOUNT_LOADING',
  ACCOUNT_ACCOUNT_LIST = 'ACCOUNT_ACCOUNT_LIST',
  ACCOUNT_ACCOUNT_LIST_ERROR = 'ACCOUNT_ACCOUNT_LIST_ERROR',
}

export enum CreditCardTypes {
  SAVED_CARD_DETAILS = 'SAVED_CARD_DETAILS',
  CREDIT_CARD_DETAILS = 'CREDIT_CARD_DETAILS',
  CREDIT_CARD_NUMBER = 'CREDIT_CARD_NUMBER',
  EXPIRY_DATE = 'EXPIRY_DATE',
  CVV_NUMBER = 'CVV_NUMBER',
  CREDIT_CARD_TYPE = 'CREDIT_CARD_TYPE',
  SELECT_AVAILABLE_CARD = 'SELECT_AVAILABLE_CARD',
  SELECT_SAVED_CARD = 'SELECT_SAVED_CARD',
  CREDIT_CARD_ERRORS = 'CREDIT_CARD_ERRORS',
  CARD_NUMBER_ERROR = 'CARD_NUMBER_ERROR',
  CVV_NUMBER_ERROR = 'CVV_NUMBER_ERROR',
  EXPIRY_DATE_ERROR = 'EXPIRY_DATE_ERROR',
  CURRENT_CARD_STEP = 'CURRENT_CARD_STEP',
}

export enum BankNameTypes {
  LOADING = 'BANKNAME_LOADING',
  GET_BANK_NAME_REQUEST = 'GET_Bank_NAME_REQUEST',
  GET_BANK_NAME_SUCCESS = 'GET_BANK_NAME_SUCCESS',
  GET_BANK_NAME_FAILURE = 'GET_BANK_NAME_FAILURE',
}
